---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: my-app-project
  source:
    repoURL: 'https://github.com/pasupuletinarasimha999/Narasimha_Final_2.git'
    path: Kubernetes/Code/dev/First_Set_Deployment
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-app
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argo
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Validate=false
    spec:
     source:
      dependsOn:
      - name: Kubernetes/Code/dev/Deployment1/application.yaml  # Dependent application (folder2/app2.yaml)
        healthy: true  # Wait for folder2 app to be healthy
