apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  # different name
  name: cert-prod
  namespace: my-app
spec:
  # dedicate secret for the TLS cert
  secretName: miniapi-production-certificate
  issuerRef:
    # referencing the production issuer
    name: letsencrypt-prod
  dnsNames:
  - www.krazyworks.shop
