---
apiVersion: v1
kind: Service
metadata:
  name: deployoneservice
  namespace: my-app
  labels:
    prometheus-enabled: "true"
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: deploy1
  type: ClusterIP