---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certloader
  namespace: argocd
  # Finalizerr that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: my-app-project2
  source:
    repoURL: 'https://github.com/pasupuletinarasimha999/Narasimha_Final_2.git'
    path: Kubernetes/Code/LetsEncryptCert/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-app
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Validate=false
