---
apiVersion: v1
kind: Namespace
metadata:
  name: my-app
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJwYXN1cHVsZXRpbmFyYXNpbWhhOTk5IiwicGFzc3dvcmQiOiJQYXN0ZXI4MTMiLCJlbWFpbCI6InBhc3VwdWxldGluYXJhc2ltaGE5OTlAZ21haWwuY29tIiwiYXV0aCI6ImNHRnpkWEIxYkdWMGFXNWhjbUZ6YVcxb1lUazVPVHBRWVhOMFpYSTRNVE09In19fQ==
kind: Secret
metadata:
  name: regcred
  namespace: my-app
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
kind: Secret
metadata:
  name: db-secrets
  namespace: my-app
type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rules
  namespace: my-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.krazyworks.shop
    # reference secret for production TLS certificate
    secretName: miniapi-production-certificate
  rules:
   - host: www.krazyworks.shop 
     http:
      paths:
      - path: /v1
        pathType: Prefix
        backend:
          service:
            name: deployoneservice
            port:
              number: 80
      - path: /v2
        pathType: Prefix
        backend:
          service:
            name: deploytwoservice
            port:
              number: 80
      - path: /v3(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: deploythreeservice
            port:
              number: 8501

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-ingress-rules
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: nginx
  rules:
   - http:
      paths:
      - path: /argocd
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 80
