---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:ravindrasinghh/argocd-setup.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBqlHsxM2
    fsH7h7kE4NuTuPAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAICuSo+7lqdaOtPgk
    EsFoNbLC09MLi6358IUJ9M2r0VBhAAAAoEcilcXmGZzchAHltweYqaueJR+IcFbzjJy/Dv
    oP++ddjVv5hiw5OKjIfnqoBf8ELSRhy8YFIL6AwVI9ReY4i20noKf8ZJvz/hhD/xDFvuF6
    JdTRBt+ptMbjB1+nv08R2NedTGkpoNcW/SbGNUqBGz33fB1hBP1xa5GRyqk66CxAj4+9p7
    poXcSN/5zYsCVS8YYO292Ke17nAJLk543mOhE=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"


# command to generate key
# ssh-keygen -t ed25519 -f ~/.ssh/argocd

